#!/bin/bash

set -o errexit
set -o nounset

# Function to handle missing output directories
mkmissingdir() {
    if [ ! -e $1 ]; then
        mkdir -p $1
    fi
}

# Function to check previous step is done
chkprevious() {
    if [ ! -e $2 ]; then
        echo "Error. ${1} expected output from previous step to exist in directory ${2}."
        exit
    fi
}

thisLauncherPath=$(readlink -f "$0")
repoPath=$(dirname "$thisLauncherPath")
cd $repoPath

doTrimAlign=false
if grep -q "trim_align: true" ./options.yaml; then
    doTrimAlign=true
fi

doCallVariants=false
if grep -q "call_variants: true" ./options.yaml; then
    doCallVariants=true
fi

publishDir=${repoPath}/output
alignmentsDir=${publishDir}/alignments
variantsDir=${publishDir}/variants
mkmissingdir $publishDir

nextflow -log ./.nextflow/nextflow.log \
    run ./source/nextflow/check_inputs.nf \
    -resume \
    -params-file ./options.yaml

if [ "$doTrimAlign" = true ]; then
    mkmissingdir $alignmentsDir
    nextflow -log ./.nextflow/nextflow.log \
        run ./source/nextflow/trim_align_reads.nf \
        -with-report $alignmentsDir/workflow_report.html \
        -resume \
        -params-file ./options.yaml \
        --publish_dir $alignmentsDir
fi

if [ "$doCallVariants" = true ]; then
    chkprevious "Step: call_variants" $alignmentsDir
    mkmissingdir $variantsDir
    nextflow -log ./.nextflow/nextflow.log \
        run ./source/nextflow/call_variants.nf \
        -with-report $variantsDir/workflow_report.html \
        -resume \
        -params-file ./options.yaml \
        --cram_dir $alignmentsDir \
        --publish_dir $variantsDir
fi

nextflow -log ./.nextflow/nextflow.log \
    run ./source/nextflow/run_multiqc.nf \
    --results_dir $publishDir \
    --publish_dir $publishDir
